'use strict';
const el = id => document.getElementById(id);
let game = new OneBlinkGame(Date.now()); let last = performance.now(); let prior = ''; let priorRound = 0;
let sound = false; let audio; let cameraStream; let interrupted = false;
const eyeNames = ['두 눈을 뜨고','왼쪽 눈을 감고','오른쪽 눈을 감고','두 눈을 감고'];
const mouthNames = ['웃는','입이 동그란','입이 일자인'];
const faceName = i => `${eyeNames[Math.floor(i / 3)]} ${mouthNames[i % 3]} 별`;
function tone(hz, length=.12, delay=0) { if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type='sine';o.frequency.setValueAtTime(hz,t);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+length);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+length);}catch{sound=false;} }
function start() { game.start(); prior='';priorRound=0;interrupted=false;last=performance.now();render();tone(523); }
el('start').addEventListener('click',start);el('retry').addEventListener('click',start);
el('reset').addEventListener('click',()=>{game=new OneBlinkGame(Date.now());prior='';priorRound=0;interrupted=false;render();});
el('sound').addEventListener('click',()=>{sound=!sound;el('sound').innerHTML=`♪ <span>${sound?'ON':'OFF'}</span>`;el('sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기');if(sound)tone(660);});
el('camera-btn').addEventListener('click',async()=>{if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=undefined;el('camera').hidden=true;el('face-note').hidden=false;el('camera-btn').textContent='카메라로 구도 보기';el('camera-status').textContent='카메라를 껐습니다. 영상은 저장하지 않았습니다.';return;}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});el('camera').srcObject=cameraStream;el('camera').hidden=false;el('face-note').hidden=true;el('camera-btn').textContent='카메라 끄기';el('camera-status').textContent='이 화면에서만 표시합니다. 저장·전송하지 않습니다.';}catch{el('camera-status').textContent='카메라를 사용할 수 없습니다. 기본 배경으로 계속 플레이할 수 있습니다.';}});
window.addEventListener('pagehide',()=>{if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&['memorize','search','correct'].includes(game.state)){interrupted=true;game.finish();render();}last=performance.now();});
function buildBoard(){const b=el('board');b.replaceChildren();b.style.gridTemplateColumns=`repeat(${game.cards.length<=9?3:4},1fr)`;b.style.setProperty('--rows',String(Math.ceil(game.cards.length/(game.cards.length<=9?3:4))));game.cards.forEach((face,i)=>{const button=document.createElement('button');button.className='tile';button.setAttribute('aria-label',`${i+1}번, ${faceName(face)}`);const img=document.createElement('img');img.src=`assets/star-${face}.svg`;img.alt='';button.append(img);button.addEventListener('click',()=>{const outcome=game.tap(i);if(outcome==='correct'){tone(660);tone(880,.15,.08);}if(outcome==='wrong')tone(180,.16);render();});b.append(button);});}
function render(){const changed=prior!==game.state||priorRound!==game.round;el('phone').dataset.state=game.state;el('phone').dataset.round=game.round;el('intro').hidden=game.state!=='intro';el('play').hidden=['intro','result'].includes(game.state);el('result').hidden=game.state!=='result';
  if(changed&&game.state==='memorize'){buildBoard();el('target').src=`assets/star-${game.target}.svg`;el('target').alt=faceName(game.target);}
  el('round-badge').textContent=`ROUND 0${game.round} / 03`;el('clock').textContent=game.remaining().toFixed(2);el('time-fill').style.transform=`scaleX(${game.remaining()/game.limit})`;el('time-fill').style.background=game.remaining()<4?'#ffac95':'#dcf291';
  el('memory').hidden=game.state!=='memorize';el('board').hidden=game.state==='memorize';el('memory-count').textContent=Math.max(0,game.phaseTime).toFixed(1);
  el('prompt').textContent=game.state==='memorize'?'이 표정을 기억해!':game.state==='correct'?'맞아, 바로 그 별!':'방금 본 별은 어디?';el('phase-hint').textContent=game.state==='memorize'?'눈과 입을 잘 봐요 · 1.5초':game.state==='correct'?'다음 별을 준비할게요':'같은 표정의 별을 탭해요';
  [...el('board').children].forEach((b,i)=>{b.disabled=game.state!=='search'||game.wrong.includes(i);b.classList.toggle('wrong',game.wrong.includes(i));b.classList.toggle('correct',game.state==='correct'&&i===game.correctIndex);});
  el('feedback').className='feedback'+(game.messageTime>0&&game.state==='search'?' bad':'');el('feedback').textContent=game.messageTime>0&&game.state==='search'?'+1초 · 눈과 입을 다시 봐요':game.state==='correct'?'GOT IT ✦':'';
  [...el('round-dots').children].forEach((d,i)=>{d.className=i<game.cleared?'done':i===game.round-1?'active':'';});
  if(changed&&game.state==='result'){const won=game.cleared===3&&!interrupted;el('result-label').textContent=interrupted?'ROUND INTERRUPTED':won?'ALL STARS FOUND':'SO CLOSE, LITTLE STAR';el('result-title').textContent=interrupted?'잠깐 멈췄어요':won?'눈치 챘네!':game.cleared>=2?'거의 다 찾았어':'다시 도전해볼까?';el('result-star').src=`assets/star-${won?4:1}.svg`;el('result-score').innerHTML=won?`${game.score().toFixed(2)}<small>초</small>`:`${game.cleared}<small>/ 3 ROUND</small>`;el('result-detail').textContent=interrupted?'화면을 벗어나 이번 기록은 종료됐어요.':won?`3라운드 성공 · 오답 가산 ${game.penalty}초 포함`:`찾는 시간 14초 종료 · 오답 가산 ${game.penalty}초`;el('splits').replaceChildren();for(let i=0;i<3;i++){const s=document.createElement('div');s.className='split';s.innerHTML=`<small>ROUND 0${i+1}</small>${game.roundTimes[i]===undefined?'—':game.roundTimes[i].toFixed(2)+'s'}`;el('splits').append(s);}el('share-line').textContent=won?'친구는 몇 초 걸릴까?':'이번엔 눈과 입을 같이 기억해봐.';if(won){celebrate();tone(523,.2);tone(659,.2,.1);tone(784,.35,.2);}}
  prior=game.state;priorRound=game.round;
}
function celebrate(){const c=el('confetti');c.replaceChildren();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<22;i++){const p=document.createElement('i');p.style.left=`${(i*43)%100}%`;p.style.background=['#dcf291','#ffd376','#f3ede0'][i%3];p.style.animationDelay=`${i*.025}s`;p.style.borderRadius=i%2?'50%':'2px';c.append(p);}setTimeout(()=>c.replaceChildren(),3500);}
function frame(now){const dt=(now-last)/1000;last=now;if(!document.hidden)game.update(dt);render();requestAnimationFrame(frame);}render();requestAnimationFrame(frame);

